# Change these first
owner: kuxav # Your GitHub organization or username, where this repository lives
repo: stats01 # The name of this repository
skipDescriptionUpdate: true

sites:
  - name: Utama/Main
    url: https://start.1423.my.id
  - name: Utama/Main at pages.dev
    url: https://1423.pages.dev
  - name: KXV x ngadem.in
    url: https://kuxav.1423.my.id
  - name: Qiqi x 1423
    url: https://77.1423.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 1.1423.my.id
  # baseUrl: /stats01
  logoUrl: https://avatars.githubusercontent.com/u/112876441?s=400&u=e0e17427add699a8808ffb7d3607bc49426fd64c&v=4
  name: ---------
  introTitle: "Halaman status"
  introMessage: Ya emang ini halaman status...
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Beranda
      href: http://1423.my.id
    - title: "77"
      href: http://77.1423.my.id
    - title: Public File
      href: http://file.1423.my.id

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
