# Change these first
owner: kuxav # Your GitHub organization or username, where this repository lives
repo: stats01 # The name of this repository
skipDescriptionUpdate: true

sites:
  - name: Utama/Main
    url: https://start.1423.my.id
  - name: Utama/Main at pages.dev
    url: https://1423.pages.dev
  - name: KXV x ngadem.in
    url: https://kuxav.1423.my.id
  - name: Qiqi x 1423
    url: https://77.1423.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: 1.1423.my.id
  # baseUrl: /stats01
  favicon: https://avatars.githubusercontent.com/u/112876441?s=400&u=e0e17427add699a8808ffb7d3607bc49426fd64c&v=4
  logoUrl: https://avatars.githubusercontent.com/u/112876441?s=400&u=e0e17427add699a8808ffb7d3607bc49426fd64c&v=4
  name: ---------
  introTitle: "Halaman status"
  introMessage: Ya emang ini halaman status...
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Beranda
      href: http://1423.my.id
    - title: "77"
      href: http://77.1423.my.id
    - title: Public File
      href: http://file.1423.my.id

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
  
  i18n:
    activeIncidents: "Insiden terjadi"
    incidentReport: "Laporan insiden #$NUMBER →"
    activeIncidentSummary: "Dibuka tgl $DATE (miladiyah) dengan $POSTS kiriman"
    incidentTitle: "Rincian insiden $NUMBER"
    incidentDetails: "Rincian insiden"
    incidentFixed: "Diperbaiki"
    incidentOngoing: "Dlm berlangsung"
    incidentOpenedAt: "Dibuka pada "
    incidentClosedAt: "Ditutup pada "
    incidentViewOnGitHub: "Lihat di Github"
    incidentCommentSummary: "Dikirmkan pada $DATE (miladiyah) oleh $AUTHOR"
    incidentBack: "← Kembali ke semua insiden"
    pastIncidents: "Insiden terakhir"
    pastIncidentsResolved: "Terselesaikan dlm $MINUTES menit dengan $POSTS kiriman"
    liveStatus: "Status"
    overallUptime: "Keseluruhan waktu aktif: $UPTIME"
    overallUptimeTitle: "Waktu aktif (semua)"
    averageResponseTime: "Rata-rata waktu respon: $TIME mildtk"
    averageResponseTimeTitle: "Rata-rata waktu balasan"
    sevelDayResponseTime: "Waktu balasan dlm sepekan"
    responseTimeMs: "Waktu balasan (mildtk)"
    responseTimeDay: "selama 24 jam"
    responseTimeWeek: "dalam sepekan"
    responseTimeMonth: "dalam sebulan"
    responseTimeYear: "dalam tahunan"
    up: "🟩 Aktif"
    down: "🟥 Gagal"
    degraded: "🟨 Impas"
    uptime: "Waktu aktif (semua)"
    uptimeDay: "dalam 24 jam"
    uptimeWeek: "dalam 1 pekan"
    uptimeMonth: "dalam 30 hari"
    uptimeYear: "dalam setahun"
    liveStatusHtmlComment: "<!--status...-->"
    allSystemsOperational: "🟩 Semua sistem operasional"
    degradedPerformance: "🟨 Impas beneran"
    completeOutage: "🟥 Kagak berfungsi"
    partialOutage: "🟧 Sebagian tdk berfungsi"
    ms: "miltdk"
    loading: "Memuat"
    navGitHub: "GitHub"
    rateLimitExceededTitle: "Batas rata-rata berlebihan"
    rateLimitExceededIntro: "Sayangnya batasan dalam permintaan sudah tidak nampung lagi. Gunakan Github Personal Access Token untuk aksesnya."
    rateLimitExceededWhatDoesErrorMean: "Ini kenapa?"
    rateLimitExceededErrorMeaning: "Ini pakai GitHub API tuk access data langsung untuk situs .... Bawaannya, GitHub terima permintaan alamat IP 60 perjam, di mana yang dipakai."
    rateLimitExceededErrorHowCanFix: "Gimana perbaikinya?"
    rateLimitExceededErrorFix: "Entahlah batasan berlaku dalam pembatasan permintaan"
    rateLimitExceededGeneratePAT: "Pelajari cara buat Personal Access Token (hanya EN)"
    rateLimitExceededHasSet: "Kan punya token akses perseorangan."
    rateLimitExceededRemoveToken: "Buang token"
    rateLimitExceededGitHubPAT: "GitHub Personal Access Token"
    rateLimitExceededCopyPastePAT: "Salin dan tempel token"
    rateLimitExceededSaveToken: "Simpan token"
    errorTitle: "Sayangnya masalah entah begitu"
    errorIntro: "Sayangnya tidak bisa entah masalah begitu"
    errorText: "Sayangnya Gorou tidak mengerti, apalagi Paimon"
    errorHome: "Kembali ke beranda"
    pastScheduledMaintenance: "Pemeliharaan terjadwal terakhir"
    scheduledMaintenance: "Pemeliharaan terjadwal"
    scheduledMaintenanceSummaryStarted: "Dimulai pada $DATE tuk $DURATION mnt"
    scheduledMaintenanceSummaryStarts: "Mulai pada $DATE dalam $DURATION mnt"
    startedAt: "Dimulai pada"
    startsAt: "Mulai pada"
    duration: "Durasi"
    durationMin: "$DURATION menit"
    incidentCompleted: "Terselesaikan"
    incidentScheduled: "Terjadwal"
    duration24H: "24 jam"
    duration7D: "7 hari"
    duration30D: "30 hari"
    duration1Y: "1 tahun"
    durationAll: "semua waktu"
    footer: "---- Entahlah, status tidak menjadi patokan"
